title: "Jaewoo Kim"
email: jw.kim@kaist.ac.kr
description: Jaewoo Kim
baseurl: ""
url: "https://www.jaewoo-space.com"

author:
  name: Jaewoo Kim
  github: jaewoo-space
  scholar: d4s06NsAAAAJ
  linkedin: jaewoo-kim-783361232

exclude:
  - Gemfile
  - Gemfile.lock

google_analytics: "G-GV2C824418"